export const EVENT_CONFIG = {
  name: "TECXWORK DEMO CAREER FAIR 2026",
  emailEventName: "TECXWORK DEMO CAREER FAIR 2026",
  tagline: "A demonstration career fair — every company, student, and booking here is fictional.",
  subtitle: "Career Fair",
  organizer: "TECXWORK Demo Organizer",
  organizerShort: "TECXWORK",
  hostedAt: "Demo Campus Convention Hall",
  hostedAtFull: "Demo Campus Convention Hall",
  date: new Date("2026-11-14T14:30:00+08:00"),
  displayDate: "November 14, 2026",
  displayYear: "2026",
  endDate: new Date("2026-11-14T17:30:00+08:00"),
  location: "Demo Campus Convention Hall",
  timezone: "Asia/Taipei",
  slotDuration: 15,
  startHour: 14,
  endHour: 17,
  endMinutes: 30,
  /** Feature flag: show newsletter opt-in on student registration */
  enableNewsletterOptIn: false,
} as const;

export const INDUSTRIES = [
  "All",
  "Technology",
  "Finance",
  "Semiconductor",
  "Manufacturing",
  "Consulting",
  "Healthcare",
  "E-Commerce",
  "Beauty",
  "Education",
  "Retail",
  "Hospitality",
  "Media",
  "Real Estate",
  "Construction",
  "Logistics",
  "Food & Beverage",
  "Energy",
  "Automotive",
  "Gaming",
  "Nonprofit",
] as const;
